(include_subdirs qualified)
(rocq.theory
 (name Extraction)
 (synopsis "Extraction entrypoints for native emitter")
 (modules (:standard))
 (theories Bytecode Assembly Stdlib)
 (rocqdep_flags
  (:standard
	-R %{project_root}/coq-compcert.3.17/lib compcert.lib
	-R %{project_root}/coq-compcert.3.17/common compcert.common
	-R %{project_root}/coq-compcert.3.17/x86 compcert.x86
	-R %{project_root}/coq-compcert.3.17/x86_64 compcert.x86_64
	-R %{project_root}/coq-compcert.3.17/backend compcert.backend
	-R %{project_root}/coq-compcert.3.17/cfrontend compcert.cfrontend
	-R %{project_root}/coq-compcert.3.17/driver compcert.driver
	-R %{project_root}/coq-compcert.3.17/cparser compcert.cparser
	-R %{project_root}/coq-compcert.3.17/flocq Flocq
	-R %{project_root}/coq-compcert.3.17/MenhirLib MenhirLib))
 (flags
  (:standard
	-R %{project_root}/coq-compcert.3.17/lib compcert.lib
	-R %{project_root}/coq-compcert.3.17/common compcert.common
	-R %{project_root}/coq-compcert.3.17/x86 compcert.x86
	-R %{project_root}/coq-compcert.3.17/x86_64 compcert.x86_64
	-R %{project_root}/coq-compcert.3.17/backend compcert.backend
	-R %{project_root}/coq-compcert.3.17/cfrontend compcert.cfrontend
	-R %{project_root}/coq-compcert.3.17/driver compcert.driver
	-R %{project_root}/coq-compcert.3.17/cparser compcert.cparser
	-R %{project_root}/coq-compcert.3.17/flocq Flocq
	-R %{project_root}/coq-compcert.3.17/MenhirLib MenhirLib)))
